# Generated by Django 5.2.12 on 2026-05-27 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price_per_hour', models.IntegerField(default=0)),
                ('length_km', models.FloatField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='tracks/')),
            ],
        ),
    ]
